package main

import (
	"fmt"
	"os"
	"strings"
	"time"
)

// emitReport renders the results as markdown to path (and always to stdout).
func emitReport(r results, path string) error {
	md := renderReport(r)

	fmt.Print(md)

	if path != "" {
		if err := os.WriteFile(path, []byte(md), 0o644); err != nil { //nolint:gosec // report is public
			return err
		}

		fmt.Fprintf(os.Stderr, "\nreport written to %s\n", path)
	}

	return nil
}

func renderReport(r results) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Spec 0008 — performance measurement report\n\n")
	fmt.Fprintf(&b, "Generated by `cmd/afmpeg-bench` — WASM (afmpeg) vs native ffmpeg on the same host, "+
		"same jobs. Source fixture: `testsrc2` "+r.fixture+" (H.264/AAC). All WASM I/O is "+
		"in-memory (afero); native writes temp files. Median of %d runs.\n\n", r.runs)

	// Environment.
	fmt.Fprintf(&b, "## Host\n\n")
	fmt.Fprintf(&b, "| | |\n|---|---|\n")
	fmt.Fprintf(&b, "| When | %s |\n", r.env.when)
	fmt.Fprintf(&b, "| Platform | %s/%s, %d CPUs |\n", r.env.goos, r.env.goarch, r.env.cpus)
	fmt.Fprintf(&b, "| Go | %s |\n", r.env.goVersion)
	fmt.Fprintf(&b, "| Native | %s |\n", r.env.ffmpeg)
	fmt.Fprintf(&b, "| LGPL module | %s |\n", orNone(r.lgplModule))
	fmt.Fprintf(&b, "| GPL module | %s |\n", orNone(r.gplModule))
	fmt.Fprintf(&b, "| Native driver | %s |\n\n", orNone(r.nativeDriver))

	// Per-workload table. Every comparison holds the encoder constant: openh264
	// against openh264, libx264 against libx264. Crossing them is worth 1.5-1.7x
	// on its own and reads as a difference between lanes when it is nothing of
	// the sort.
	fmt.Fprintf(&b, "## Every lane, both encoders\n\n")
	fmt.Fprintf(&b, "Absolute medians. Read across a row only within one encoder — openh264 is "+
		"1.5–1.7× faster than libx264 at these settings, so a cross-encoder comparison "+
		"measures the encoder, not the lane.\n\n")
	fmt.Fprintf(&b, "| Workload | Encoder | WASM | Native driver | ffmpeg CLI |\n")
	fmt.Fprintf(&b, "|---|---|--:|--:|--:|\n")

	for _, w := range r.workloads {
		fmt.Fprintf(&b, "| %s | openh264 | %s | %s | %s |\n", w.name,
			cell(w.haveOpenh264, w.openh264), cell(w.haveNativeDrvOH, w.nativeDrvOH),
			cell(w.haveNativeOH, w.nativeOH))
		fmt.Fprintf(&b, "| %s | libx264 | %s | %s | %s |\n", w.name,
			cell(w.haveX264, w.x264), cell(w.haveNativeDrvX264, w.nativeDrvX264),
			cell(w.haveNative, w.native))
	}

	fmt.Fprintf(&b, "\n")

	for _, w := range r.workloads {
		fmt.Fprintf(&b, "- **%s** — %s\n", w.name, w.desc)
	}

	fmt.Fprintf(&b, "\n")

	// The two ratios a reader actually needs, each holding the encoder constant.
	fmt.Fprintf(&b, "## The two ratios that matter\n\n")
	fmt.Fprintf(&b, "**WASM cost** is how much the sandbox costs against the same engine running "+
		"natively. **Bridge cost** is how much afmpeg's native driver costs against bare ffmpeg — "+
		"the price of the IPC bridge and the no-host-disk guarantee.\n\n")
	fmt.Fprintf(&b, "| Workload | Encoder | WASM cost (WASM ÷ driver) | Bridge cost (driver ÷ CLI) |\n")
	fmt.Fprintf(&b, "|---|---|--:|--:|\n")

	for _, w := range r.workloads {
		for _, row := range []struct {
			enc                        string
			wasm, drv, cli             stat
			haveWasm, haveDrv, haveCLI bool
		}{
			{"openh264", w.openh264, w.nativeDrvOH, w.nativeOH, w.haveOpenh264, w.haveNativeDrvOH, w.haveNativeOH},
			{"libx264", w.x264, w.nativeDrvX264, w.native, w.haveX264, w.haveNativeDrvX264, w.haveNative},
		} {
			wasmCost, bridge := "—", "—"
			if row.haveWasm && row.haveDrv && row.drv.median() > 0 {
				wasmCost = fmt.Sprintf("%.1f×", ratio(row.wasm.median(), row.drv.median()))
			}
			if row.haveDrv && row.haveCLI && row.cli.median() > 0 {
				bridge = fmt.Sprintf("%.2f×", ratio(row.drv.median(), row.cli.median()))
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", w.name, row.enc, wasmCost, bridge)
		}
	}

	fmt.Fprintf(&b, "\nA bridge cost below 1.00× means the driver beat the CLI on that job.\n\n")

	// Preset sweep.
	if len(r.presets) > 0 {
		fmt.Fprintf(&b, "## x264 preset sweep — transcode\n\n")
		fmt.Fprintf(&b, "| Preset | WASM libx264 | Native libx264 | Native multiple |\n")
		fmt.Fprintf(&b, "|---|--:|--:|--:|\n")

		for _, p := range r.presets {
			fmt.Fprintf(&b, "| %s | %s | %s | %.1f× |\n",
				p.preset, dur(p.x264.median()), dur(p.native.median()), ratio(p.x264.median(), p.native.median()))
		}

		fmt.Fprintf(&b, "\n")
	}

	// Fleet throughput.
	if r.fleet != nil {
		f := r.fleet
		speedup := ratio(f.serial, f.parallel)

		fmt.Fprintf(&b, "## Fleet throughput (instance-level parallelism)\n\n")
		fmt.Fprintf(&b, "%d transcode jobs (x264 `ultrafast`), one Runtime (serial) vs a pool of %d Runtimes:\n\n", f.jobs, f.workers)
		fmt.Fprintf(&b, "| Mode | Wall clock | Throughput |\n|---|--:|--:|\n")
		fmt.Fprintf(&b, "| Serial (1 Runtime) | %s | %.1f jobs/s |\n", dur(f.serial), perSec(f.jobs, f.serial))
		fmt.Fprintf(&b, "| Fleet (%d Runtimes) | %s | %.1f jobs/s |\n", f.workers, dur(f.parallel), perSec(f.jobs, f.parallel))
		fmt.Fprintf(&b, "\n**Speedup: %.1f×** across %d cores.\n\n", speedup, f.workers)
	}

	// Frames.
	if r.frames != nil {
		fmt.Fprintf(&b, "## Thumbnail (frames op — decode + scale, minimal encode)\n\n")
		fmt.Fprintf(&b, "| | WASM | Native | Native multiple |\n|---|--:|--:|--:|\n")
		fmt.Fprintf(&b, "| single frame @2s → png | %s | %s | %.1f× |\n\n",
			dur(r.frames.x264.median()), dur(r.frames.native.median()), ratio(r.frames.x264.median(), r.frames.native.median()))
	}

	// Failures (recorded, non-fatal) — honesty about what didn't run.
	if len(r.notes) > 0 {
		fmt.Fprintf(&b, "## Measurements that errored\n\n")
		fmt.Fprintf(&b, "Recorded, not fatal — the rest of the run proceeded:\n\n")

		for _, n := range r.notes {
			fmt.Fprintf(&b, "- %s\n", n)
		}

		fmt.Fprintf(&b, "\n")
	}

	fmt.Fprintf(&b, "## Caveats\n\n")
	fmt.Fprintf(&b, "- **Not apples-to-apples beyond the encoder.** WASM is single-threaded and `--disable-asm`; "+
		"native ffmpeg uses all cores + SIMD. The multiple is an *upper bound* on the gap, not a like-for-like.\n")
	fmt.Fprintf(&b, "- **I/O differs by design** — WASM keeps everything in afero (RAM); native uses temp files.\n")
	fmt.Fprintf(&b, "- **openh264 ≠ libx264** in speed *and* quality/size; the openh264 column is informational.\n")
	fmt.Fprintf(&b, "- The `-Oz` vs `-O2/-O3` module-build axis (spec 0008 §3.2) needs a rebuilt module and is not measured here.\n")

	return b.String()
}

// dur formats a duration compactly (ms under 1s, else seconds).
func dur(d time.Duration) string {
	if d == 0 {
		return "—"
	}

	if d < time.Second {
		return fmt.Sprintf("%d ms", d.Milliseconds())
	}

	return fmt.Sprintf("%.2f s", d.Seconds())
}

func cell(have bool, s stat) string {
	if !have {
		return "—"
	}

	return dur(s.median())
}

func ratio(a, b time.Duration) float64 {
	if b == 0 {
		return 0
	}

	return float64(a) / float64(b)
}

func perSec(jobs int, d time.Duration) float64 {
	if d == 0 {
		return 0
	}

	return float64(jobs) / d.Seconds()
}

func orNone(s string) string {
	if s == "" {
		return "_(not provided)_"
	}

	return "`" + s + "`"
}
